// MISC VARS
export const GET_ERRORS = "GET_ERRORS";

// USER VARS
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER = "GET_USER";
export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";

// TRIP VARS
export const ADD_TRIP = "ADD_TRIP";
export const ADD_TRIP_RELATIONSHIP = "ADD_TRIP_RELATIONSHIP";
export const ADD_USER_TO_TRIP = "ADD_USER_TO_TRIP";

export const GET_TRIP = "GET_TRIP";
export const GET_TRIPS = "GET_TRIPS";
export const GET_OWNED_TRIPS = "GET_OWNED_TRIPS";
export const CHANGE_SEARCHABLE_TRIPS = "CHANGE_SEARCHABLE_TRIPS";

export const SET_TRIP_MODAL = "SET_TRIP_MODAL";

export const DELETE_TRIP = "DELETE_TRIP";
export const DELETE_TRIP_SUCCESS = "DELETE_TRIP_SUCCESS";
export const DELETE_TRIP_FAILURE = "DELETE_TRIP_FAILURE";
